### ISSUE TITLE
Botones sin accion

### ISSUE THREAD

**Issue by NicoGonzalez94** [emiliolj1/Final_Project_Front_G2_Rolling#49]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que los botones redirijan a dicho sitio o una page 404.

## Resultado actual

• Lo botones no cumplen ninguna funcion.

## Captura

![image](https://github.com/emiliolj1/Final_Project_Front_G2_Rolling/assets/166792979/7837d52e-0077-4acd-8c01-9e565c08b4da)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Marcestordeur** [comment]
Hello NicoGonzales, please check the proyect again! we resolve all problems
