### ISSUE TITLE
Form contacto

### ISSUE THREAD

**Issue by NicoGonzalez94** [emiliolj1/Final_Project_Front_G2_Rolling#50]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que no se permita colocar numeros ni signos en el nombre.
• Encontrar un limite de caracteres a colocar en el mensaje.
• Que no muestre informacion por consola.

## Resultado actual

• Se permite colocar numeros y signos en el nombre.
• No hay un limite de caracteres a colocar en el mensaje.
• Se muestra informacion por consola.

## Captura

![image](https://github.com/emiliolj1/Final_Project_Front_G2_Rolling/assets/166792979/44c89b24-f92e-4589-a23d-4742e9163f42)
![image](https://github.com/emiliolj1/Final_Project_Front_G2_Rolling/assets/166792979/bf1342e6-ad27-4557-ac0a-31039b8fe2ef)
![image](https://github.com/emiliolj1/Final_Project_Front_G2_Rolling/assets/166792979/9fd6be15-c269-4503-84f3-2a1e6879f75a)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Marcestordeur** [comment]
Hello NicoGonzales, please check the proyect again! we resolve all problems
