### ISSUE TITLE
Form registro

### ISSUE THREAD

**Issue by NicoGonzalez94** [emiliolj1/Final_Project_Front_G2_Rolling#51]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que no se permita colocar numeros ni signos en el nombre.
•Que no se muestre informacion por consola.

## Resultado actual

• Se permite colocar numeros y signos en el nombre.
• Una vez registrado se muestra informacion importante por consola.

## Captura

![image](https://github.com/emiliolj1/Final_Project_Front_G2_Rolling/assets/166792979/208e5056-dd1b-477f-9fba-e5ac66dc5676)
![image](https://github.com/emiliolj1/Final_Project_Front_G2_Rolling/assets/166792979/50837228-3a9a-4369-9b44-82d6576e9f05)
![image](https://github.com/emiliolj1/Final_Project_Front_G2_Rolling/assets/166792979/2f4e64c5-ed80-4bc2-b444-8e2bcb933e8c)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Marcestordeur** [comment]
Hello NicoGonzales, please check the proyect again! we resolve all problems
